unstable_features = true
max_width = 120
comment_width = 120
wrap_comments = true
newline_style = "unix"
use_field_init_shorthand = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
