[package]
name = "editor"
version = "0.1.0"
authors = ["Alex Bates <hi@imalex.xyz>"]
edition = "2018"

[features]
default = ["wee_alloc"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["console"] }
wee_alloc = { version = "0.4", optional = true } # slower but much smaller
console_error_panic_hook = "0.1"
yew = "0.17"
