[package]
name = "pm64"
version = "0.1.0"
authors = ["Alex Bates <hi@imalex.xyz>"]
edition = "2018"

[dependencies]
lazy_static = "1"
smallvec = { version = "1.5", features = ["write"] } # TODO: remove
log = "0.4"
id-arena = "2.2"
midly = { version = "0.5", optional = true }
