[package]
name = "codec"
version = "0.1.0"
authors = ["Alex Bates <hi@imalex.xyz>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.117", features = ["derive"] }
smallvec = { version = "1.5.0", features = ["write", "serde"] }
by_address = "1.0.4"

[dev-dependencies]
insta = "1.3.0"
