[package]
name = "codec"
version = "0.1.0"
authors = ["Alex Bates <hi@imalex.xyz>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
smallvec = { version = "1.5", features = ["write", "serde"] }

[dev-dependencies]
insta = "1.3"
