[package]
name = "codec"
version = "0.1.0"
authors = ["Alex Bates <hi@imalex.xyz>"]
edition = "2018"

[dependencies]
smallvec = { version = "1.5.0", features = ["write"] }
by_address = "1.0.4"
tinystr = "0.4.1"
#log = "0.4.11"
