name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: npm ci
        working-directory: ./editor

      - uses: jetli/wasm-pack-action@v0.3.0

      - uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          package_root: ./electron
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
