name: Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Download baserom
      run: curl -Lo baserom.z64 $BASEROM_URL
      env:
        BASEROM_URL: ${{ secrets.BASEROM_URL }}

    - name: Extract assets from baserom
      run: python3 pm64/tests/bin/extract.py baserom.z64

    - uses: Swatinem/rust-cache@v1

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --no-fail-fast
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: clippy, rustfmt
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: check
    - uses: jetli/wasm-pack-action@v0.3.0
    - run: yarn install
    - run: yarn run lint
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
