name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Download baserom
      run: curl -Lo baserom.z64 $BASEROM_URL
      env:
        BASEROM_URL: ${{ secrets.BASEROM_URL }}

    - name: Extract assets from baserom
      run: python3 pm64/tests/bin/extract.py baserom.z64

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --no-fail-fast
