name: Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Download test data
      run: cd pm64/tests/bin && curl -Lo mamar_test_data.zip $TEST_DATA_URL && unzip mamar_test_data.zip
      env:
        TEST_DATA_URL: https://drive.google.com/uc?export=download&id=1EY_nx_6xtpApgh3qyGivgU0OcpzkKRn0

    - uses: Swatinem/rust-cache@v1

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --no-fail-fast
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: clippy, rustfmt
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: check
    - uses: jetli/wasm-pack-action@v0.3.0
    - run: yarn install
    - run: yarn run lint
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
